
clear
#JANGAN DI RECODE YA
#DENGER GK LU
#AJG
cowsay -f eyes "WARNING" | lolcat
figlet -f slant "FAJAR CYBER"|lolcat
echo "-------------------------KING-----------------------------"
echo "AUTHOR : FAJAR CYBER"|lolcat
echo "KONTAK : 08817805411"|lolcat
echo      "JANGAN DI RECODE"|lolcat
echo "-------------------------KING-----------------------------"
echo "GUNAKAN DENGAN BIJAK"
echo
read -p "MASUKAN NOMOR TARGET : " read tr
echo "SILAKAN ISI BERAPA JUMLAH SPAM"|lolcat
echo "BATAS JUMLAH SPAM 1000"|lolcat
echo
read -p "JUMLAH : " read tr
echo " [WAIT]..."
echo "STOPP CTRL +Z"|lolcat
echo "##########################################################"
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
echo "[succes] BERHASIL ✓"|lolcat
